version: '3.8'

services:
  php:
    image: php:8.3-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./stack/app:/var/www/html # PHP code will be in `stack/app` directory
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./stack/app:/var/www/html # Serve the same files
      - ./stack/nginx_conf:/etc/nginx/conf.d # Custom Nginx config
      - ./stack/certs:/etc/nginx/certs # Map SSL certs
    ports:
      - "8081:80"
      - "1443:443"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb-instance
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mIABcuDjBV5q0F5
      MYSQL_DATABASE: index
      MYSQL_USER: index
      MYSQL_PASSWORD: mIABcuDjBV5q0F5
    volumes:
      - ./stack/mariadb_data:/var/lib/mysql # MariaDB data will be in `stack/mariadb_data` directory
      - ./stack/mariadb_conf:/etc/mysql/conf.d # Optional: custom MariaDB config
    ports:
      - "33317:3306" # Use a non-default port to avoid conflicts
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb-instance
      PMA_PORT: 3306 # Use local/internal port instead of mapped port
      PMA_USER: index
      PMA_PASSWORD: mIABcuDjBV5q0F5
    ports:
      - "8283:80" # Change if this port is already in use
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
